[package]
name = "cards"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
eframe = "0.27.2"
egui = "0.27.2"
env_logger = "0.11.3"
sqlite = "0.36.0"
